name: release-containerd

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref (e.g. v1.6.15)'
        required: true
        type: string
      repo:
        description: 'Override default repo'
        required: false
        type: string
      release:
        description: 'Release type'
        required: false
        default: 'prerelease'
        type: choice
        options:
          - pushonly
          - draft
          - prerelease
          - release

jobs:
  release:
    uses: ./.github/workflows/.build.yml
    with:
      name: containerd
      release: ${{ inputs.release }}
      envs: |
        PKG_REPO=${{ inputs.repo }}
        PKG_REF=${{ inputs.ref }}
    secrets: inherit
