name: release-compose

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref (e.g. v2.15.1)'
        required: true
        type: string
      repo:
        description: 'Override default repo'
        required: false
        type: string
      release:
        description: 'Release type'
        required: false
        default: 'pushonly'
        type: choice
        options:
          - pushonly
          - draft
          - prerelease
          - release
      distro:
        description: 'Single distro to build for'
        required: false
        type: string
        default: ''

jobs:
  release:
    uses: ./.github/workflows/.build.yml
    with:
      name: compose
      release: ${{ inputs.release }}
      distro: ${{ inputs.distro }}
      envs: |
        PKG_REPO=${{ inputs.repo }}
        PKG_REF=${{ inputs.ref }}
    secrets: inherit
