name: validate

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Run
        uses: docker/bake-action@v6
        with:
          source: .
          targets: validate
